### ISSUE TITLE
Compilation error with revision 4a31817

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#24]
While attempting to build revision 4a31817, I get the following errors.  I believe the "unmappable character" errors have not prevented successful compilation in the past.

````
gov/uspto/patent/model/NplCitation.java:[8,69] unmappable character for encoding UTF-8
gov/uspto/patent/model/NplCitation.java:[8,81] unmappable character for encoding UTF-8
gov/uspto/patent/model/NplCitation.java:[8,91] unmappable character for encoding UTF-8
gov/uspto/patent/model/CountryCodeHistory.java:[116,61] unmappable character for encoding UTF-8
gov/uspto/patent/doc/greenbook/Greenbook.java:[98,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[102,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[105,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[108,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[111,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
```
Thanks

**Comment by bgfeldm** [comment]
I added DotCode class for greenbook, the special characters introduced must have changed the default compiler encoding.   I have made changes and believe it should work now.

**Comment by pedagogly** [comment]
Thanks; the latest revision fixed some of the errors, but I'm still getting the following:
````
gov/uspto/patent/doc/greenbook/Greenbook.java:[96,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[100,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[103,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[106,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
gov/uspto/patent/doc/greenbook/Greenbook.java:[109,46] cannot find symbol
  symbol:   method setKindCode(java.lang.String)
  location: variable publicationId of type gov.uspto.patent.model.DocumentId
````

**Comment by bgfeldm** [comment]
Fixed forgot to checkin the updated DocumentId class.

**Comment by pedagogly** [comment]
Works now; thanks.
